In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pickle

In [3]:
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
df.drop(['RowNumber',"CustomerId",'Surname'], axis=1, inplace=True)

In [6]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
df.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
labelencoder_gender=LabelEncoder()
df['Gender']=labelencoder_gender.fit_transform(df['Gender'])
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [16]:
onehotencoder_geography=OneHotEncoder()
geo_encoded = onehotencoder_geography.fit_transform(df[['Geography']]).toarray()

In [18]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehotencoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [19]:
df = pd.concat([df.drop('Geography', axis=1),geo_encoded_df], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [20]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(labelencoder_gender, file=file)

In [22]:
with open("onehot_encoder_geography.pkl","wb") as file:
    pickle.dump(obj=onehotencoder_geography, file=file)

In [23]:
x=df.drop(['Exited'],axis=1)
y=df['Exited']

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.2, random_state=42)

#scaling:
scaler=StandardScaler()
scaler.fit_transform(x_train)
scaler.transform(x_test)

#creating scaler pickle file
with open("scaler.pkl","wb") as file:
    pickle.dump(obj=scaler, file=file)

## ANN Implementation:

In [ ]:
import tensorflow as tf